-- AlterEnum
ALTER TYPE "NodeType" ADD VALUE IF NOT EXISTS 'SWITCH';
ALTER TYPE "NodeType" ADD VALUE IF NOT EXISTS 'IF';
ALTER TYPE "NodeType" ADD VALUE IF NOT EXISTS 'MERGE';
ALTER TYPE "NodeType" ADD VALUE IF NOT EXISTS 'LOOP';
ALTER TYPE "NodeType" ADD VALUE IF NOT EXISTS 'WEBHOOK_TRIGGER';
