-- AlterEnum
ALTER TYPE "NodeType" ADD VALUE IF NOT EXISTS 'CHAT_TRIGGER';
ALTER TYPE "NodeType" ADD VALUE IF NOT EXISTS 'GITHUB';
ALTER TYPE "NodeType" ADD VALUE IF NOT EXISTS 'AIRTABLE';
ALTER TYPE "NodeType" ADD VALUE IF NOT EXISTS 'POSTGRES';
ALTER TYPE "NodeType" ADD VALUE IF NOT EXISTS 'WHATSAPP';

-- AlterEnum
ALTER TYPE "CredentialType" ADD VALUE IF NOT EXISTS 'GITHUB';
ALTER TYPE "CredentialType" ADD VALUE IF NOT EXISTS 'AIRTABLE';
ALTER TYPE "CredentialType" ADD VALUE IF NOT EXISTS 'POSTGRES';
ALTER TYPE "CredentialType" ADD VALUE IF NOT EXISTS 'WHATSAPP';
