import { findTriggerNodes, startWorkflowExecution } from "@/inngest/utils";
import { secretsMatch } from "@/lib/webhook-security";
import { type NextRequest, NextResponse } from "next/server";
import { NodeType } from "@prisma/client";

export async function POST(request: NextRequest) {
    try {
        const url = new URL(request.url);

        const workflowId =
            url.searchParams.get("workflowId");

        if (!workflowId) {
            return NextResponse.json(
                {
                    success: false,
                    error:
                        "Missing required query parameter: workflowId",
                },
                { status: 400 }
            );
        }

        const triggerNodes = await findTriggerNodes(
            workflowId,
            NodeType.GOOGLE_FORM_TRIGGER
        );

        if (triggerNodes.length === 0) {
            return NextResponse.json(
                {
                    success: false,
                    error:
                        "Workflow not found, not active, or it has no Google Form trigger",
                },
                { status: 404 }
            );
        }

        // The Apps Script generated by the trigger's dialog sends this secret
        const provided =
            request.headers.get("x-webhook-secret") ||
            url.searchParams.get("secret") ||
            "";

        const authorized = triggerNodes.some((node) => {
            const secret = (node.data as { secret?: string } | null)?.secret;

            return !!secret && secretsMatch(provided, secret);
        });

        if (!authorized) {
            return NextResponse.json(
                {
                    success: false,
                    error:
                        "Invalid or missing webhook secret. Copy the Apps Script again from the Google Form trigger node.",
                },
                { status: 401 }
            );
        }

        const body = await request.json();

        const formData = {
            formId: body.formId,
            formTitle: body.formTitle,
            responseId: body.responseId,
            timestamp: body.timestamp,
            respondentEmail:
                body.respondentEmail,
            responses: body.responses,
            raw: body,
        };

        // Trigger an Inngest Job
        await startWorkflowExecution({
            workflowId,
            trigger: NodeType.GOOGLE_FORM_TRIGGER,

            initialData: {
                googleForm: formData,
            },
        });

        return NextResponse.json(
            { success: true },
            { status: 200 }
        );
    } catch (error) {
        console.error(
            "Google form webhook error:",
            error
        );

        return NextResponse.json(
            {
                success: false,
                error:
                    "Failed to process Google Form submission",
            },
            { status: 500 }
        );
    }
}
