-- AlterEnum
ALTER TYPE "NodeType" ADD VALUE IF NOT EXISTS 'RESPOND_TO_WEBHOOK';
ALTER TYPE "NodeType" ADD VALUE IF NOT EXISTS 'ERROR_TRIGGER';
ALTER TYPE "NodeType" ADD VALUE IF NOT EXISTS 'STOP_AND_ERROR';
ALTER TYPE "NodeType" ADD VALUE IF NOT EXISTS 'TELEGRAM_TRIGGER';
ALTER TYPE "NodeType" ADD VALUE IF NOT EXISTS 'WHATSAPP_TRIGGER';
ALTER TYPE "NodeType" ADD VALUE IF NOT EXISTS 'GMAIL';
ALTER TYPE "NodeType" ADD VALUE IF NOT EXISTS 'SPLIT_OUT';
ALTER TYPE "NodeType" ADD VALUE IF NOT EXISTS 'AGGREGATE';
ALTER TYPE "NodeType" ADD VALUE IF NOT EXISTS 'SORT';
ALTER TYPE "NodeType" ADD VALUE IF NOT EXISTS 'LIMIT';
ALTER TYPE "NodeType" ADD VALUE IF NOT EXISTS 'REMOVE_DUPLICATES';
ALTER TYPE "NodeType" ADD VALUE IF NOT EXISTS 'SUMMARIZE';
ALTER TYPE "NodeType" ADD VALUE IF NOT EXISTS 'EXECUTE_WORKFLOW';
ALTER TYPE "NodeType" ADD VALUE IF NOT EXISTS 'EXECUTE_WORKFLOW_TRIGGER';
ALTER TYPE "NodeType" ADD VALUE IF NOT EXISTS 'CHAT_MODEL';

-- AlterEnum
ALTER TYPE "CredentialType" ADD VALUE IF NOT EXISTS 'HTTP_BASIC_AUTH';
ALTER TYPE "CredentialType" ADD VALUE IF NOT EXISTS 'HTTP_HEADER_AUTH';
ALTER TYPE "CredentialType" ADD VALUE IF NOT EXISTS 'HTTP_BEARER_AUTH';
ALTER TYPE "CredentialType" ADD VALUE IF NOT EXISTS 'GOOGLE_OAUTH2';
ALTER TYPE "CredentialType" ADD VALUE IF NOT EXISTS 'OPENAI_COMPATIBLE';

-- The response a Respond to Webhook node wants the waiting caller to get
ALTER TABLE "Execution" ADD COLUMN "webhookResponse" JSONB;
