-- AlterEnum
ALTER TYPE "NodeType" ADD VALUE IF NOT EXISTS 'DEEPSEEK';
ALTER TYPE "NodeType" ADD VALUE IF NOT EXISTS 'KIMI';
ALTER TYPE "NodeType" ADD VALUE IF NOT EXISTS 'QWEN';
ALTER TYPE "CredentialType" ADD VALUE IF NOT EXISTS 'DEEPSEEK';
ALTER TYPE "CredentialType" ADD VALUE IF NOT EXISTS 'KIMI';
ALTER TYPE "CredentialType" ADD VALUE IF NOT EXISTS 'QWEN';
