-- AlterEnum
ALTER TYPE "NodeType" ADD VALUE IF NOT EXISTS 'EDIT_FIELDS';
ALTER TYPE "NodeType" ADD VALUE IF NOT EXISTS 'TWILIO';
ALTER TYPE "NodeType" ADD VALUE IF NOT EXISTS 'JIRA';
ALTER TYPE "NodeType" ADD VALUE IF NOT EXISTS 'HUBSPOT';
ALTER TYPE "NodeType" ADD VALUE IF NOT EXISTS 'MYSQL';
ALTER TYPE "NodeType" ADD VALUE IF NOT EXISTS 'RESEND';
ALTER TYPE "NodeType" ADD VALUE IF NOT EXISTS 'SENDGRID';
ALTER TYPE "NodeType" ADD VALUE IF NOT EXISTS 'TYPEFORM_TRIGGER';

-- AlterEnum
ALTER TYPE "CredentialType" ADD VALUE IF NOT EXISTS 'TWILIO';
ALTER TYPE "CredentialType" ADD VALUE IF NOT EXISTS 'JIRA';
ALTER TYPE "CredentialType" ADD VALUE IF NOT EXISTS 'HUBSPOT';
ALTER TYPE "CredentialType" ADD VALUE IF NOT EXISTS 'MYSQL';
ALTER TYPE "CredentialType" ADD VALUE IF NOT EXISTS 'RESEND';
ALTER TYPE "CredentialType" ADD VALUE IF NOT EXISTS 'SENDGRID';
